### ISSUE TITLE
Tests fail on Ubuntu due to missing -lpam

### ISSUE THREAD

**Issue by mgorny** [google/google-authenticator-libpam#109]
```
$ ./tests/pam_google_authenticator_unittest 
Testing base32 encoding
Testing base32 decoding
Testing HMAC_SHA1
Loading PAM module
dlopen(): ./.libs/libpam_google_authenticator_testing.so: undefined symbol: pam_strerror
```

Apparently the Makefile is missing `-lpam` for the testing module. To be honest, I have no clue why it works on Gentoo but fails on the Ubuntu setup Semaphore is using:

```
$ uname -a
Linux semaphore-1807 4.4.0-130-generic #156~14.04.1-Ubuntu SMP Thu Jun 14 13:51:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ThomasHabets** [comment]
Curious.

`./tests/pam_google_authenticator_unittest` links to `-lpam` but `libpam_google_authenticator_testing.so` does not.

I'll add it. Let me know if that fixes it for you. It worked before and after for me.

**Comment by ThomasHabets** [comment]
Thanks! This fixed the test on travis-CI for GCC.
