### ISSUE TITLE
google-authentication-libpam is not working with xrdp on Ubuntu 18

### ISSUE THREAD

**Issue by Sas002** [google/google-authenticator-libpam#110]
google-authentication-libpam is not working with xrdp on Ubuntu 18. Is there any documentation of configuring google-authentication on Ubuntu18 with xrdp . I followed the standard steps but google-auth is not prompting for code

**Comment by ThomasHabets** [comment]
>  I followed the standard steps

There are no standard steps. Please specify exactly what you tried.

**Comment by Sas002** [comment]
I tried steps frm https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04 . It seems login using ssh is working with google-auth but not xrdp login is not at all asking for google-auth code . It is just accepting username and password and never ask for code

**Comment by Sas002** [comment]
I followed https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04    step 1 , step and step3

**Comment by ThomasHabets** [comment]
It's seems likely that the xrdp protocol doesn't support a secondary password prompt. I'd recommend you configure the PAM module to take the OTP from the password. See [this section of the README](https://github.com/google/google-authenticator-libpam#try_first_pass--use_first_pass--forward_pass) for more information.

**Comment by Sas002** [comment]
My pam file /etc/pam.d/sshd  looks below 
# PAM configuration for the Secure Shell service
  
# Standard Un*x authentication.
#@include common-auth

# Disallow non-root logins when /etc/nologin exists.
account    required     pam_nologin.so

# Uncomment and edit /etc/security/access.conf if you need to set complex
# access limits that are hard to express in sshd_config.
# account  required     pam_access.so

# Standard Un*x authorization.
@include common-account

# SELinux needs to be the first session rule.  This ensures that any
# lingering context has been cleared.  Without this it is possible that a
# module could execute code in the wrong domain.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close

# Set the loginuid process attribute.
session    required     pam_loginuid.so

# Create a new session keyring.
session    optional     pam_keyinit.so force revoke

# Standard Un*x session setup and teardown.
@include common-session

# Print the message of the day upon successful login.
# This includes a dynamically generated part from /run/motd.dynamic
# and a static (admin-editable) part from /etc/motd.
session    optional     pam_motd.so  motd=/run/motd.dynamic
session    optional     pam_motd.so noupdate

# Print the status of the user's mailbox upon successful login.
session    optional     pam_mail.so standard noenv # [1]

# Set up user limits from /etc/security/limits.conf.
session    required     pam_limits.so

# Read environment variables from /etc/environment and
# /etc/security/pam_env.conf.
session    required     pam_env.so # [1]
# In Debian 4.0 (etch), locale-related environment variables were moved to
# /etc/default/locale, so read that as well.
session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale

# SELinux needs to intervene at login time to ensure that the process starts
# in the proper default security context.  Only sessions which are intended
# to run in the user's context should be run after this.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open

# Standard Un*x password updating.
#@include common-password
**auth required pam_google_authenticator.so forward_pass**

Here ssh is working fine with just google-authenticator code . No password is required.  For xrdp session still I am not able to login

**Comment by ThomasHabets** [comment]
To paste data without formatting, use tripple-backticks \`

OK, so you have *only* the GA OTP PAM module. Then you don't need `forward_pass`.

Next step is checking the logs. Probably `/var/log/auth.log`. Maybe adding `debug` option to GA to get more debugging output.

**Comment by Sas002** [comment]
It seems I am only able to use GA OTP on ssh session . XRDP is just working on username and password . Even if I use forward_pass or not . I am using xrdp  with xrdp-sesman  session

**Comment by Sas002** [comment]
It seems for adding GA with xrdp , I need to add below config but after adding below config xrdp login session stop working . I am not able to select any option for xrdp login . Is there any specific configuration I need to add for xrdp for making GA OTP ?

login, edit /etc/pam.d/common-auth:

sudo vim /etc/pam.d/common-auth
and now add this auth required pam_google_authenticator.so above the line auth    [success=1 default=ignore]      pam_unix.so nullok_secure then save the file.

**Comment by Sas002** [comment]
Finally I made it working just with OTP ( no password ) . It is working fine with ssh as well as xrdp session. I just need to provide username and code from google-authenticator mobile app and xrdp session login just works. Could not manage to config both password and OTP for xrdp . with ssh it is working fine .

xrdp to work with one time code from GA  cat /etc/pam.d/xrdp-sesman 
#%PAM-1.0
#@include common-auth
#@include common-account
#@include common-session
#@include common-password
auth required pam_google_authenticator.so  ---------> This is the only config added and rest all should be disabled

**Comment by ThomasHabets** [comment]
I would expect this to work:

```
auth required pam_google_authenticator.so forward_pass
auth required pam_unix.so use_first_pass
```

And then enter "password012345" as password (hmm, or is it "012345password"?) where 012345 is the OTP.

**Comment by Sas002** [comment]
I will test and confirm .

**Comment by Sas002** [comment]
It is working perfect for xrdp session using sesman. Just I do not get two screens for password and OTP but that is something missing from xrdp not from GA. Thanks a lot .

**Comment by brijeshjaiswal** [comment]
Can you please confirm step by step process for    xrdp configuration with Google authenticator.

**Comment by brijeshjaiswal** [comment]
> I would expect this to work:
> 
> ```
> auth required pam_google_authenticator.so forward_pass
> auth required pam_unix.so use_first_pass
> ```
> And then enter "password012345" as password (hmm, or is it "012345password"?) where 012345 is the OTP.

This worked awesome. But I was thinking to have a separate field in first login screen for OTP/Token. So that in first field we will enter username, in second field password and last filed will contain token in mask or visible.
Request you to please check and help me. Appreciate if OTP will be in masked format.  
![untitled](https://user-images.githubusercontent.com/43043598/48509518-5fc07200-e877-11e8-869f-4a1a869e22dd.png)

**Comment by brijeshjaiswal** [comment]
> > I would expect this to work:
> > ```
> > auth required pam_google_authenticator.so forward_pass
> > auth required pam_unix.so use_first_pass
> > ```
> > And then enter "password012345" as password (hmm, or is it "012345password"?) where 012345 is the OTP.
> 
> This worked awesome. But I was thinking to have a separate field in first login screen for OTP/Token. So that in first field we will enter username, in second field password and last filed will contain token in mask or visible.
> Request you to please check and help me. Appreciate if OTP will be in masked format.
> ![untitled](https://user-images.githubusercontent.com/43043598/48509518-5fc07200-e877-11e8-869f-4a1a869e22dd.png)

* Note - Right now i have only created field by making an entry in xrdp.ini only.  Right now i dont have knowledge to how to map the OTP filed with the program. 
![untitled1](https://user-images.githubusercontent.com/43043598/48509790-13c1fd00-e878-11e8-8c1f-53db1205d8d3.png)

**Comment by ThomasHabets** [comment]
Try playing around with `authtok_prompt=otp` or similar. I think the "extra password" that the OTP is is an extra key/value, that is keyed off of that.

I'm not sure though.

Try it, and see if it works.

**Comment by brijeshjaiswal** [comment]
> Try playing around with `authtok_prompt=otp` or similar. I think the "extra password" that the OTP is is an extra key/value, that is keyed off of that.
> 
> I'm not sure though.
> 
> Try it, and report back if it works.

But where i have make "authtok_prompt=otp" this entry. Basically on which file.

**Comment by brijeshjaiswal** [comment]
I tried but it didn't work. The reason is simple that I have just created field called OTP but not aware from where it's going to call the function. Like username or password it usually calls the function and then it does validation.

**Comment by brijeshjaiswal** [comment]
Requesting you please help me with that part.

**Comment by ThomasHabets** [comment]
I don't understand the question.

**Comment by ThomasHabets** [comment]
> I have just created field called OTP

What's a "field"? In what?

> not aware from where it's going to call the function

What function?

> Like username or password it usually calls the function and then it does validation.

That's… not a description that fits well with how PAM works, if that's what you're referring to.

But really it sounds like you're asking how xrdp is supposed to work. I have no idea. I know fairly well how PAM works though.

Maybe something from [this issue](https://github.com/google/google-authenticator-libpam/issues/112) could help you, but really I'm just guessing what your question is.

**Comment by wisoez** [comment]
auth required pam_google_authenticator.so forward_pass
auth required pam_unix.so use_first_pass

I added to /etc/pam.d/xrdp-sesman, but not work :(

**Comment by ThomasHabets** [comment]
Logs are needed to debug.

**Comment by wisoez** [comment]
Dear @ThomasHabets 
This is my config: /etc/pam.d/xrdp-sesman
![image](https://user-images.githubusercontent.com/10806362/99018283-451b5380-258c-11eb-814d-aa5763271a41.png)

This is auth log: /var/log/auth.log
![Screenshot_2](https://user-images.githubusercontent.com/10806362/99018162-071e2f80-258c-11eb-85bf-0f562a8170ed.png)

This is xRDP log: /var/log/xrdp.log
![Screenshot_3](https://user-images.githubusercontent.com/10806362/99018505-cf63b780-258c-11eb-9103-30d7f6d82be4.png)

This is /var/log/xRDP-sesman.log
![Screenshot_4](https://user-images.githubusercontent.com/10806362/99018547-f02c0d00-258c-11eb-8ec4-401bcdd71c97.png)

Thank you so much!

**Comment by Alvaro1316** [comment]
> Logs are needed to debug.

Hello Dear @ThomasHabets Can you help me?
I install Ubuntu 20.04 and I already make the changes in  /etc/pam.d/xrdp-sesman
![Captura de pantalla 2021-11-22 132047](https://user-images.githubusercontent.com/94866189/142922254-8edf8f96-d0c4-4c69-8480-c547db29b46d.png)
Also I make changes in the xrdp.ini to show the opt code.
But still no working

**Comment by ThomasHabets** [comment]
Sorry, I've not set up xrdp, and standard log and complete config rules apply.
