### ISSUE TITLE
.google_authenticator file permissions issue

### ISSUE THREAD

**Issue by Anvano** [google/google-authenticator-libpam#115]
After setting up parameter secret=/var/unencrypted-home/${USER}/.google_authenticator  option   (Encrypted home directories),  I have noticed error  message in auth.log

"sshd(pam_google_authenticator)[15301]: Secret file permissions are 0400. Allowed permissions are 0600"

Ok. I have changed permissions  to  0600.  Double checked it!
After login  - permissions on this file has been reset to  0400.

I have tried once more: 
1) changed permissions to 0600
2) tried to login
3) checked permission - and again they has been changed to 0400

It seems to be that  pam_google_authenticator.so  changing file permissions upon login to 0400. 
Thus preventing subsequent login attempts with error  message  above.

**Comment by Anvano** [comment]
I have checked source code and found out than  allowed_perm = 0600 hardcoded  for the  .google_authenticator  file.

But every login attempt method  write_file_contents()  is called.  I has fragment 
if (fchmod(fd, 0400)) {    <====   ????  why 0400 ????
    err = errno;
    goto cleanup;
 }

Seems as bug to me.  
You are resetting permissions to 0400 upon each login attempt,  then  checking permissions  for  allowed_perm = 0600  in next login attempt.   
How this supposed to work ?

**Comment by Anvano** [comment]
-

**Comment by ThomasHabets** [comment]
To clarify for future readers: Allowed permissions are 0400 (read) and 0200 (write), which combines to 0600. The message means no *other* bits are allowed. And the difference between 0600 and 0400 doesn't prevent login.
