### ISSUE TITLE
have to disable common-auth for 2FA ssh login

### ISSUE THREAD

**Issue by darima001** [google/google-authenticator-libpam#124]
I am setting up 2FA password-free ssh login to a Ubuntu 18.04 server. The goal is to use as two factors: a) SSH public key and b) googe-authenticator's one-time password.

Unfortunately, SSH prompts me for password unless I disable common-auth in /etc/pam.d/ssh. Setting ChallengeResponseAuthentication to no, causes the failure to start sshd.service. For the details of my setup see below.

My questions are: 
* Is it safe to disable '@include common-auth' in /etc/pam.d/sshd?
* Is there better way to accomplish my goal?

Thank you for your time!

My setup:

Command used for installation:
	sudo apt-get install libpam-google-authenticator

Edit /etc/pam.d/sshd: 
	#@include common-auth
	auth required pam_google_authenticator.so

Edit /etc/ssh/sshd_config:
	PasswordAuthentication no
	ChallengeResponseAuthentication yes
	AuthenticationMethods publickey,keyboard-interactive

**Comment by ThomasHabets** [comment]
`/etc/pam.d/common-auth` presumably uses `pam_unix`, so yeah if you don't want to use passwords then you can't include `common-auth`.

And no, that's the way to get pubkey+OTP.

**Comment by darima001** [comment]
We got answer to our question on libpam.
Our solution is the correct one.

Darima

On 19 Mar 2019, at 14:56, Thomas Habets <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #124<https://github.com/google/google-authenticator-libpam/issues/124>.

**Comment by ThomasHabets** [comment]
Great!

Sorry for the late reply. I was on vacation.
