### ISSUE TITLE
The 2nd argument 'home' of function 'strcpy()' is tained

### ISSUE THREAD

**Issue by 360CodeSafe** [google/google-authenticator-libpam#132]
in line 843:
https://github.com/google/google-authenticator-libpam/blob/842142d52328baa6076826428fe040db98aab82a/src/google-authenticator.c#L843

The 2nd argument 'home' of function 'strcpy()' is assigned in line 833:
    const char *home = getenv("HOME");

**Comment by ThomasHabets** [comment]
So what? `$HOME` comes from the user, yes. So does `-s`.
