### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by 360CodeSafe** [google/google-authenticator-libpam#133]
in line 126：
https://github.com/google/google-authenticator-libpam/blob/842142d52328baa6076826428fe040db98aab82a/src/base32_prog.c#L126

Memory is allocated, but never freed at the end of function.

**Comment by ThomasHabets** [comment]
Yeah. The function is `main`, so it doesn't really matter. I assume this is done by a tool?

1. Maybe this tool should ignore `main`?
2. This tool failed to find the equivalent "leak" under `mode == DECODE_STRING`
