### ISSUE TITLE
Feature Request:  Mobile app access security

### ISSUE THREAD

**Issue by mike15623** [google/google-authenticator-libpam#135]
Aloha,
First off, thanks to all devs for the hard work!
I have a small (I think) request - the mobile apps should request a fingerprint, FaceID, or PIN before letting the user access 2FA codes.
Thanks again,
Mike

**Comment by ThomasHabets** [comment]
This repo is about the PAM module, as the name of the repo implies.

Also I'm pretty sure there's already a tracking issue in the correct repo for this feature.
