### ISSUE TITLE
Failure to allocate memory after 1.07 update

### ISSUE THREAD

**Issue by Duffyx** [google/google-authenticator-libpam#146]
Dec 31 10:51:26 vados kernel: Dec 31 10:51:26 vados sshd(pam_google_authenticator)[94478]: Out of memory
Dec 31 10:51:26 vados kernel: Dec 31 10:51:26 vados sshd[92735]: error: PAM: Authentication error for illegal user xxxx from 10.0.0.115
Dec 31 10:51:38 vados kernel: Dec 31 10:51:38 vados sshd(pam_google_authenticator)[94634]: Short (-1) mem allocation failed
Dec 31 10:51:38 vados kernel: Dec 31 10:51:38 vados sshd(pam_google_authenticator)[94634]: Out of memory

Hi, I'm maintaining the port of FreeBSD, and after updating it to 1.07 something changed in the behavior. Each time someone logs in and pam_google_authenticator is up for its authentication I get the error you see above.

I'm not out of memory at all. So seems like a bug.

**Comment by ThomasHabets** [comment]
Indeed negative 1 bytes is a short allocation.

**Comment by ThomasHabets** [comment]
Oh, I see it. It's comparing a `size_t` to see if it's less than zero.
Since commit becf7abfe5c884dcc8d8a9a2db48a12912cde410
Doh.

**Comment by ThomasHabets** [comment]
Single-character fix: `ssize_t` instead of `size_t` on line 189. Or https://github.com/google/google-authenticator-libpam/commit/1927ade9f6172783b4a14df1a62c05bf336096aa.

Could you confirm that this fixes it, and I'll tag a 1.08?

**Comment by Duffyx** [comment]
Just tested your patch, works fine. Thanks for the quick response!

**Comment by ThomasHabets** [comment]
1.08 tagged, with only diff from 1.07 being this fix.

**Comment by stefansedich** [comment]
Just got bit by this in Alpine 3.11 for our OpenVPN instances, for anyone suffering the same installing from the edge repo will give you 1.08:

```
echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
apk add --update google-authenticator@edge
```
