### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/google-authenticator-libpam#149]
Memory is allocated
https://github.com/google/google-authenticator-libpam/blob/bc1af869b17e24b98e14d2e53cf35365e6e55324/src/google-authenticator.c#L109

Potential leak of memory pointed to by 'buf '
https://github.com/google/google-authenticator-libpam/blob/bc1af869b17e24b98e14d2e53cf35365e6e55324/src/google-authenticator.c#L118

**Comment by ThomasHabets** [comment]
You can't really leak memory if you terminate the process. That's not how `malloc` works. This isn't SHM memory.

**Comment by ThomasHabets** [comment]
I see you're spamming other projects with incorrect reports too. Please stop wasting people's time.

Examples:
* https://github.com/uber/statsrelay/issues/75
* https://github.com/vmware/open-vm-tools/issues/395
* https://github.com/google/google-authenticator-libpam/issues/149
* https://github.com/google/google-authenticator-libpam/issues/150
