### ISSUE TITLE
No "Invalid verification code" received, but validation still fails

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#15]
_From @ThomasHabets on October 10, 2014 8:7_

Original [issue 373](https://code.google.com/p/google-authenticator/issues/detail?id=373) created by pcamilleri@smartasset.com on 2014-03-28T22:01:36.000Z:

I've installed pam_google_authenticator on Centos 6.5, and set up a simple pam config to test it out (together with Authen::PAM::Simple) in perl.

The pam config is called &quot;openvpn&quot; and simply contains:
auth required pam_warn.so
auth required pam_google_authenticator.so

My perl script simply tries to authenticate a user (&quot;test&quot;) with their google authenticator key.

If I use an old/invalid code, I see the following 2 lines (debug message followed by invalid verification code) in /var/log/secure (as expected)

Mar 28 17:52:55 wall perl: pam_warn(openvpn:auth): function=[pam_sm_authenticate] service=[openvpn] terminal=[&lt;unknown&gt;] user=[test] ruser=[&lt;unknown&gt;] rhost=[&lt;unknown&gt;]
Mar 28 17:52:55 wall openvpn(pam_google_authenticator)[23943]: Invalid verification code

When I use a &quot;valid&quot; code, I see the debug line, but no &quot;Invalid verification code&quot;, YET pam still fails to authenticate.

(I've also tried this setup with openvpn and keep having the same issue -- no &quot;Invalid verification code&quot; message, yet I just can't authenticate).

Any ideas? 

thanks

_Copied from original issue: google/google-authenticator#372_

**Comment by ThomasHabets** [comment]
Comment [#1](https://code.google.com/p/google-authenticator/issues/detail?id=373#c1) originally posted by pcamilleri@smartasset.com on 2014-03-31T15:22:24.000Z:

The issue was in the pam.d configuration. For anyone interested, this should work:

account     required      pam_unix.so
account     required      pam_permit.so
auth        requisite     pam_google_authenticator.so forward_pass
auth        required      pam_unix.so use_first_pass

**Comment by BouchaaraAdil** [comment]
> The issue was in the pam.d configuration. For anyone interested, this should work:
account required pam_unix.so
account required pam_permit.so
auth requisite pam_google_authenticator.so forward_pass
auth required pam_unix.so use_first_pass

tried this didn't work, could you help ?
https://github.com/google/google-authenticator-libpam/issues/116

**Comment by BouchaaraAdil** [comment]
@ThomasHabets @alex @kpumuk @kruton 🙏
