### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/google-authenticator-libpam#150]
Memory is allocated
https://github.com/google/google-authenticator-libpam/blob/fe17bd27235a09e3eb7d755afac8c33fab617ac9/src/base32_prog.c#L130

never free it
https://github.com/google/google-authenticator-libpam/blob/fe17bd27235a09e3eb7d755afac8c33fab617ac9/src/base32_prog.c#L158

**Comment by ThomasHabets** [comment]
Again, just like #149: No, that's not how memory allocation works.
