### ISSUE TITLE
he asks me again for credentials after one hour

### ISSUE THREAD

**Issue by ortiga88** [google/google-authenticator-libpam#157]
I have the following configuration:

```
auth requisite /lib/x86_64-linux-gnu/security/pam_google_authenticator.so secret=/etc/google-authenticator/${USER}/.google_authenticator forward_pass debug echo_verification_code
auth required pam_unix.so use_first_pass

account [success=1 new_authtok_reqd=done default=ignore]        pam_unix.so

account requisite                       pam_deny.so

account required                        pam_permit.so
```

I get in the vpn client `killing expired key` why is this???

**Comment by ThomasHabets** [comment]
What is this, openvpn? This is a question for whatever program you're using PAM with.

**Comment by ortiga88** [comment]
> ¿Qué es esto, openvpn? Esta es una pregunta para cualquier programa con el que esté utilizando PAM.

already but I have implemented openvpn with this module as and then it disconnects me at the time it may be that I have to establish a grace period as the documentation says

**Comment by ThomasHabets** [comment]
This is a question for openvpn.
