### ISSUE TITLE
A problem with hotmail.com Google Accounts "user@hotmail.com like Google Account" do not have the code email to verify

### ISSUE THREAD

**Issue by Neustradamus** [google/google-authenticator-libpam#159]
Hello Google team,

I do not know, how I can send this issue but Google Accounts created with Hotmail addresses "user@hotmail.com like Google Account" (and maybe other Microsoft mail addresses or other mail addresses of the World) can not received the email with the Google Code to confirm that we are the user.

But the blocked alert mail has been received.

I see that it is not new:
- https://support.google.com/mail/forum/AAAAK7un8RU7uDa33Sgx5c

Can you solve it?

Thanks in advance.

**Comment by ThomasHabets** [comment]
This is not Google support.
