### ISSUE TITLE
Typo in pam_google_authenticator.c, line 341

### ISSUE THREAD

**Issue by r5r3** [google/google-authenticator-libpam#166]
In `setgroup` `HAS_SETFSUID` instead of `HAVE_SETFSUID`is used. The former is always undefined and `setegid` is always called instead of `setfsgid`.

**Comment by ThomasHabets** [comment]
Thanks!

**Comment by ThomasHabets** [comment]
I just tagged release 1.09. This is the only notable change since 1.08.

**Comment by r5r3** [comment]
Thanks for the very fast response!
