### ISSUE TITLE
Backup google authenticator

### ISSUE THREAD

**Issue by daniel1302** [google/google-authenticator-libpam#169]
Hi, I need to backup google authenticator configured for openvpn. How Can I do it?
I use this command to generate barcode:

```
su -c "google-authenticator -t -d -r3 -R30 -W -f -l \"${LABEL}\" -s /etc/openvpn/google-authenticator/${USERNAME}" - gauth
```

**Comment by ThomasHabets** [comment]
Are you asking for the *backup codes*, or how to *back up the config*?

**Comment by daniel1302** [comment]
Sorry I got some troubles with backup config, but I had bug in my restore script. It did not created users. 

My flow is:

### Backup:

1. Backup /etc/openvpn/keys
2. Backup /etc/openvpn/google-authenticator
3. Backup ovpn files

### Restore:
1. Download /etc/openvpn/keys
2. Download /etc/openvpn/google-authenticator
3. Set permissions for /etc/openvpn/google-authenticator 
   - 0700 for /etc/openvpn/google-authenticator
   - 0400 for /etc/openvpn/google-authenticator/*
4. Download ovpn files
5. Create users based on /etc/openvpn/google-authenticator/*

Now it is working fine :)
