### ISSUE TITLE
Why is the shared secret used in libpam only 80 bits? 

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#18]
_From @ThomasHabets on October 10, 2014 8:7_

Original [issue 340](https://code.google.com/p/google-authenticator/issues/detail?id=340) created by terrycwk1994 on 2013-11-07T02:52:37.000Z:

The code in `libpam/google-authenticator.c` defines the shared secret to be 80 bits.
\# define SECRET_BITS    80    // Must be divisible by eight

This appears not to conform with [RFC 4226](http://www.ietf.org/rfc/rfc4226.txt) that states:

   R6 - The algorithm MUST use a strong shared secret.  The length of
   the shared secret MUST be at least 128 bits.  This document
   RECOMMENDs a shared secret length of 160 bits.

I suggest that the code be patched to modify this to 160 bits, which conforms with the recommendation by RFC 4226 and is what Google is using for 2FA with their own services.

_Copied from original issue: google/google-authenticator#339_

**Comment by ThomasHabets** [comment]
Migrated comment:

http://security.stackexchange.com/questions/45053/why-does-google-cripple-the-2fa-google-authenticator-pam-module

**Comment by ThomasHabets** [comment]
Comment [#1](https://code.google.com/p/google-authenticator/issues/detail?id=340#c1) originally posted by akshay@10gen.com on 2013-11-24T19:19:21.000Z:

http://security.stackexchange.com/questions/45053/why-does-google-cripple-the-2fa-google-authenticator-pam-module

**Comment by ThomasHabets** [comment]
Comment [#2](https://code.google.com/p/google-authenticator/issues/detail?id=340#c2) originally posted by akshayk on 2013-11-27T01:54:19.000Z:

http://security.stackexchange.com/questions/45053/why-does-google-cripple-the-2fa-google-authenticator-pam-module

**Comment by ThomasHabets** [comment]
Looks answered on stackexchange.

**Comment by martey** [comment]
I think the existence of fb9a769ab11cf1cac0d06af41b73bfbd5fcfb0af (which changes `SECRET_BITS` from 80 to 128) is also worth mentioning, since it invalidates this question and fixes any potential issue.
