### ISSUE TITLE
qr code regeneration

### ISSUE THREAD

**Issue by dustiestgolf** [google/google-authenticator-libpam#192]
Is it possible to generate the qr code after the initial setup process has been completed?

**Comment by ThomasHabets** [comment]
There's no tooling to generate QR code from a `.google_authenticator` config yet, no.

Nothing prevents making one, and shouldn't be hard.

**Comment by dustiestgolf** [comment]
Cool thanks for the info I'll look into it.

**Comment by ThomasHabets** [comment]
There isn't a tool for it, but should be easy to make one that takes the secret from the config file.
