### ISSUE TITLE
Building from source seems to put pam_google_authenticator.so in the wrong place

### ISSUE THREAD

**Issue by uajqq** [google/google-authenticator-libpam#198]
I'm on Ubuntu 18 and when I install the package from apt, the library is placed in `/usr/lib/x86_64-linux-gnu/security/`. However, building it from source places the library in `/usr/local/lib/security`, and I can't login as a result. Placing a symlink in `/usr/lib/x86_64-linux-gnu/security/` corrects the issue, and I suppose I could add `/usr/local/lib/security` to the path somehow, but is there something I'm missing to make this work easier?

**Comment by ThomasHabets** [comment]
You can always provide the full path to the `.so` file in your PAM config.

Other than that I think this is a question for your distribution maintainers, why they don't have `/usr/local/lib/security` in the default PAM path.

**Comment by uajqq** [comment]
> You can always provide the full path to the `.so` file in your PAM config.

Interesting--I tried that before and it wasn't working, but I just tried it again and it works now. Maybe I had a typo. 

> Other than that I think this is a question for your distribution maintainers, why they don't have /usr/local/lib/security in the default PAM path.

I'm using the standard `apt-get` Ubuntu repo. As others have noted, it hasn't been updated since 2017; hence me trying to install from source. Who maintains that?

**Comment by ThomasHabets** [comment]
Should be as standard as it gets on Linux, yes. But installing outside of `/usr/local` by default is a no-no. So if indeed there is a path inside `/usr/local` that is searched by default, then I'd like to know how to find that out at build time.
