### ISSUE TITLE
Why is there no 2fa prompt for "su - user" but 2fa prompt for "su user"?

### ISSUE THREAD

**Issue by miguelmota** [google/google-authenticator-libpam#210]
Hi, I'm trying to require 2fa for `su`. The issue is that there is no 2fa prompt when running `su - <user>` (with dash) but there is a prompt when running `su <user>` (no dash)?

I added this to `/etc/pam.d/su`

```
auth required pam_google_authenticator.so
```

The rest of config is default on arch linux

```
#%PAM-1.0
auth required pam_google_authenticator.so
auth            sufficient      pam_rootok.so
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            required        pam_unix.so
account         required        pam_unix.so
session         required        pam_unix.so
password        include         system-auth
```

![DeepinScreenshot_select-area_20220321121325](https://user-images.githubusercontent.com/168240/159347170-bb0d91de-85d2-4742-85dd-5498a9030f5a.png)

![DeepinScreenshot_select-area_20220321121347](https://user-images.githubusercontent.com/168240/159347161-4ea10853-a5d5-4af4-b9c6-e65b891dd76f.png)

Any ideas on how to make 2fa prompt show for `su -`? thanks!

**Comment by ThomasHabets** [comment]
From the `su` manual on my system:

```
FILES
       /etc/pam.d/su
           default PAM configuration file

       /etc/pam.d/su-l
           PAM configuration file if --login is specified
```

`--login` is the same as `-`, per same manual.
