### ISSUE TITLE
REHL 9 and related, EPEL-Release 9

### ISSUE THREAD

**Issue by Clifra-Jones** [google/google-authenticator-libpam#218]
Currently this is unavailable in EPEL-Release 9 for RHEL 9 (and its derivitives). Will this eventually be available?

Sorry if this is not the right place to ask this.

**Comment by ThomasHabets** [comment]
More of a question for RedHat. Was it ever in their release? In any case packaging for distributions I'd say is out of scope here. Maybe put a request in with RedHat?
