### ISSUE TITLE
module for nginx

### ISSUE THREAD

**Issue by kuznetcoff777** [google/google-authenticator-libpam#220]
Why there is an apache module exists but no such a module for nginx?

**Comment by ThomasHabets** [comment]
I'm not aware of any apache module.

**Comment by kuznetcoff777** [comment]
https://code.google.com/archive/p/google-authenticator-apache-module/

**Comment by ThomasHabets** [comment]
Ok. Another project once existed that implemented an apache module, not updated in almost 10 years.

Feel free to implement whatever you want for nginx. Both HOTP and TOTP are open standards.
