### ISSUE TITLE
Configuring name

### ISSUE THREAD

**Issue by LB22** [google/google-authenticator-libpam#222]
I apologize for opening this issue, but I have searched far and wide for an answer.

So I have installed this on my Ubuntu server and all works great. It's just that for when I scan the QR code and add it in my google authenticator app, I see the hostname of my server and the user I did it with `hostname (user@hostname)`

for example: `eu1-prod (root@eu1-prod)`

How can I configure this to use perhaps `domain.tld (user)` instead?

I see that other applications use `AppName` or `AppName (email)`.

I know I could edit this myself inside Google Authenticator, but I want to set this on the server, did I miss some name flag?

**Comment by akerl** [comment]
https://github.com/google/google-authenticator-libpam/blob/master/man/google-authenticator.1.md#general-options

**Comment by ThomasHabets** [comment]
Try it.
