### ISSUE TITLE
Getting the time that google-authenticator is using

### ISSUE THREAD

**Issue by bahjat1993** [google/google-authenticator-libpam#223]
### System information
Operating system: Ubuntu 20

How do i get the time that my google authenticator is using? It keeps giving me an incorrect time however i know for a fact my ubuntu machine has the correct time

**Comment by ThomasHabets** [comment]
It's using the system time: https://github.com/google/google-authenticator-libpam/blob/master/src/pam_google_authenticator.c#L762
