### ISSUE TITLE
Where is the content of the configuration file documented?

### ISSUE THREAD

**Issue by mrandreastoth** [google/google-authenticator-libpam#238]
Where is the content of ~/.google_authenticator documented to allow it to be properly edited?

**Comment by ThomasHabets** [comment]
[In FILEFORMAT.](https://github.com/google/google-authenticator-libpam/blob/master/FILEFORMAT)

Sorry for not saying that in the other bug. I thought it wasn't documented, but apparently I misremembered.

**Comment by ThomasHabets** [comment]
That file looks correct, but not complete. It doesn't include the grace period feature.

But for your purposes I don't think (the optional) grace periods matter.

**Comment by mrandreastoth** [comment]
No worries and thanks for the link 👍

**Comment by mrandreastoth** [comment]
By the way, which is the grace period question out of the following...?

![Setup options.](https://www.linuxbabe.com/wp-content/uploads/2017/05/ssh-2fa-debian.webp)

**Comment by ThomasHabets** [comment]
Grace period is currently not part of the user config, but instead a PAM module wide option. [See README](https://github.com/google/google-authenticator-libpam#grace_periodseconds).

I would not recommend enabling grace periods, and would not want the choice of enabling it to be up to the user. A possible alternative implementation would be to have a module option of allowing grace period, and then letting users enable it.
