### ISSUE TITLE
Time Sync issue?  some trouble in authentication

### ISSUE THREAD

**Issue by ellen-mindshift** [google/google-authenticator-libpam#239]
### System information
Operating system : Ubuntu 18.04
Do you use selinux? : No

### Steps to reproduce

1. …

### What I expected would happen

SSH Connection with google authenticator app

### What actually happened

It works fine. But it seems like things go out of sync every few months.

For example, I set up each Authenticator on two servers.

One server has been working well for nearly 3 years now,
but the other server loses connection every once in a while (as short as 3 months, as long as 6 months), 
so I mount the volume on another server, access it indirectly, sync again, and then fix it.
The server specifications and environment are set the same, but in this case, I have no idea which part of the setting I need to adjust. How should I fix it?

Is there any suggestions / solutions for someone like me ?

Thanks.

### PAM config

Paste the relevant parts of your PAM config

```
auth required pam_google_authenticator.so nullok
```

### If SSH: SSH config

Paste the relevant parts of `/etc/ssh/sshd_config` or equivalent.

```
UsePAM yes
AuthenticationMethods password publickey, keyboard-interactive
```

### If not SSH: That program's config, and logs

```
paste here
```

### Contents of `/var/log/auth.log` or equivalent

```
paste here
```

**Comment by akerl** [comment]
The thing that keeps it in sync is accurate time. The only way for it to fall out of sync is for the clock on your server or your mobile device to be inaccurate. So I’d start with that.

**Comment by ellen-mindshift** [comment]
Thanks everybody. Issue resolved.
I just switch to counter based OTP, that's enough.
