### ISSUE TITLE
The URL of the QR code generated with google-authenticator-libpam results in a 404 error and the QR code is not displayed.

### ISSUE THREAD

**Issue by s-hirai** [google/google-authenticator-libpam#244]
I installed google-authenticator-libpam on centos and use it for two-step authentication when connecting to the server via SSH.
For a few days now, the QR code generated using the google-authenticator-libpam command will complete successfully, but the URL that displays the QR code will result in a 404 error and the QR code will no longer be displayed. If there has been any recent changes or if you know anything about the cause, could you please give me some advice?

**Comment by ThomasHabets** [comment]
This is, presumably, what was fixed in https://github.com/google/google-authenticator-libpam/pull/243/files ?

**Comment by ThomasHabets** [comment]
Could you confirm that changing the URL in that way fixes it?

**Comment by ThomasHabets** [comment]
Actually, we should probably remove that URL generator completely. It's one thing to trust Google, but quite another to trust whoever owns that `.io` domain.

I hear people preparing to disagree about that, but this *is* a Google project. So I'll remove it.

If you want a QR code, instead make sure you have libqrencode installed.

**Comment by s-hirai** [comment]
When I tried changing the URL, I was able to display the QR code. I will consider what to do about the URL generator. thank you very much.

**Comment by ThomasHabets** [comment]
Ok, I got confirmation that the `www.google.com/chart` interface is gone and not coming back.

Because I don't want to point this kind of sensitive data to a third party site, unless someone comes up with something better then the only way forward is that the user has `libqrencode` intalled, and therefore gets the QR code on the terminal, generated locally.

**Comment by nyetsche** [comment]
This is exactly the code fix for which I was considering a fork. Instead, when might be the next release be?

**Comment by ThomasHabets** [comment]
@nyetsche I ripped out the URL generating code. You're saying you want this feature, but allow for third party rendering services?

You don't need to fork. You can just make it configurable, maybe via a command line, and I'd accept it.

**Comment by nyetsche** [comment]
I meant workplace fork, not public, but regardless my question was if there would be a formal release soon - 1.09 was released (tagged) in 2020: https://github.com/google/google-authenticator-libpam/tags

**Comment by ThomasHabets** [comment]
You're right, it's been a while. Done. Just tagged 1.10.
