### ISSUE TITLE
Pulled google-authenticator-libpam  into yocto build, library is not getting installed 

### ISSUE THREAD

**Issue by raviteja-b** [google/google-authenticator-libpam#245]
### Describe the bug
Created yocto build with google-authenticator-libpam recipe file, noticed that pam_google_authenticator.so
 library is not installed 
 
### To Reproduce
Steps to reproduce the behaviour:
1.  create yocto build with google-authenticator-libpam recipe
2. binary file installed but library  pam_google_authenticator.so is not installed on machine.

### Expected behavior
Yocto Build with provide recipe file should install library onto roots

### Environment
arm arch

**Comment by ThomasHabets** [comment]
I've never heard of yocto. A quick googling says that you should probably contact whoever made a yocto.build file, because something's wrong with it?

**Comment by raviteja-b** [comment]
> I've never heard of yocto. A quick googling says that you should probably contact whoever made a yocto.build file, because something's wrong with it?

here is recipe file, can you please check what's wrong with it
https://git.yoctoproject.org/meta-security/tree/recipes-security/google-authenticator-libpam/google-authenticator-libpam_1.09.bb?h=master

**Comment by ThomasHabets** [comment]
I have no idea. I've never heard of yocto or recipe files until today. Looks... plausible?
