### ISSUE TITLE
google-authenticator returns an invalid URL for QR Code

### ISSUE THREAD

**Issue by dariosusman** [google/google-authenticator-libpam#251]
google-authenticator displays a URL to display the QR code that no longer exists. Returns HTTP 404.

### Steps To Reproduce
1. run google-authenticator to generate a QR code
 `/usr/bin/google-authenticator -C -t -D -w 15 -u -l <LABEL> -i <ISSUER> -f -s /opt/google-auth/$1`
2. Go to provided URL with any browser.
Example:
`https://www.google.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/<LABEL>%3Fsecret%3D<SECRET>%26issuer%3D<ISSUER>`

https://www.google.com/chart and/or https://chart.googleapis.com/chart return HTTP 404

### Expected behavior
The URL should either work or the URL should no longer be used if its service has been deprecated.

### Environment
 - OS: Debian
 - Version 12
- Do you use selinux? No

Thank you.

Best regards,
Dario Susman

**Comment by akerl** [comment]
What version are you running? That code path was fully removed in https://github.com/google/google-authenticator-libpam/commit/0a0ebf2e2a5e6d288347208c4d21d6c1aebae4f5 , which should be present in v1.10
