### ISSUE TITLE
(Question)how to handle password change of user with pam_google_authenticator.so configuration

### ISSUE THREAD

**Issue by raviteja-b** [google/google-authenticator-libpam#255]
I have updated PAM configuration to include google-authenticator configuration as suggested 
I have setup secret key and TOTP authentication works for each user.

Here is list of PAM files I have updated to configure pam_google_authenticator 
cat /etc/pam.d/common-password 
password        [success=ok default=die]    pam_google_authenticator.so

cat /etc/pam.d/common-auth 
auth required pam_google_authenticator.so forward_pass nullok

cat /etc/pam.d/common-account
account [success=ignore default=ignore]   pam_google_authenticator.so

I keep getting error while I try to change password of any user on that system

```
passwd
passwd: Module is unknown
passwd: password unchanged

```
` passwd[487]: PAM unable to resolve symbol: pam_sm_chauthtok`

did I miss any PAM configuration? why does password change of user fails?
how to handle password change of user with google-authenticator enabled as 2-Factor auth?

**Comment by ThomasHabets** [comment]
As I told you in https://github.com/google/google-authenticator-libpam/issues/252, this is not implemented.

**Comment by raviteja-b** [comment]
> As I told you in #252, this is not implemented.

can you please help clarify on where it needs to be implemented?

**Comment by ThomasHabets** [comment]
As the error message says, it needs [`pam_sm_chauthtok`](https://www.man7.org/linux/man-pages/man3/pam_sm_chauthtok.3.html) to be implemented.

This issue was not filed as a feature request. Also while I'd accept will written PRs, filing a feature request likely won't make anybody actually do it.

**Comment by raviteja-b** [comment]
with google-authenticator pam configuration, I see this error trace 
`PAM unable to resolve symbol: pam_sm_acct_mgmt`

do you think pam_sm_acct_mgmt() needs to be implemented similar to pam_sm_chauthtok ??

**Comment by ThomasHabets** [comment]
Don't know. Sounds like it.
