### ISSUE TITLE
Copy .google_authenticator between two boxes

### ISSUE THREAD

**Issue by iamaravindragu** [google/google-authenticator-libpam#256]
Dear Team , 

  I'm trying to migrate the server from Old operating system [ubuntu 14.04 ] to the newer one [ Amazon linux 2023 ] . 
In OLD Box I've Google_authenticator configured that was working fine . I tried copy that file to newer one . Post copying I try to take the ssh of new machine and It's not taking the code from app but to my surprise backup/emergency codes are accepted .  

Error:

sshd[3208]: error: PAM: Authentication failure for User from IP.

--
Aravindan R

**Comment by ThomasHabets** [comment]
That should work. Something must be different in the config. No config provided though, so not troubleshootable.

**Comment by ThomasHabets** [comment]
Oh, and we have issue templates for a reason.
