### ISSUE TITLE
Running google-authenticator in quiet mode still asks you a question

### ISSUE THREAD

**Issue by proskilly** [google/google-authenticator-libpam#259]
I'd like to run this:
google-authenticator --time-based --disallow-reuse --force --qr-mode=ansi --emergency-codes=10 --quiet

But run it automatically via a C# app when there isn't a user present, so I was hoping to run it in quiet mode where everything it needs to know is within the original command's options and it doesn't need to ask any questions.
I'm happy to capture the output from the command (QR code and emergency codes).

Running the above command shows this question:

"By default, a new token is generated every 30 seconds by the mobile app.
In order to compensate ....
Do you want to do so? (y/n) "

**Comment by ThomasHabets** [comment]
You can specify `-w` `-r` and `-R`, and you'll have no questions asked.

**Comment by proskilly** [comment]
Thank you, it does still prompt you "Enter code from app (-1 to skip):"

It would be good if there was a way to get it to go with the -1 to skip automatically and didn't ask.
