### ISSUE TITLE
Question: why does google authenticator ask for totp for user which does not exist on system

### ISSUE THREAD

**Issue by raviteja-b** [google/google-authenticator-libpam#260]
pam google-authenticator was looking for totp for the user which does not existing on system and this user does not have secret key setup also.

Usually LDAP Users do not exists on the system, google authenticator should ignore users which does not exist on the system 
so using google authenticator breaking LDAP users. 

```
pam_google_authenticator: user("prashanth") not found
pam_google_authenticator: No secret configured for user prashanth, asking for code anyway.
pam_google_authenticator: Did not receive verification code from user
pam_google_authenticator: Did not receive verification code from user

```

how to disable this behavior in pam_google_authenticator

**Comment by ThomasHabets** [comment]
The user doesn't exist *and* doesn't have a secret key set up, eh?

Maybe a job for `pam_succeed_if`?

```
auth [default=1 success=ignore] pam_succeed_if.so quiet uid > 0
auth pam_google_authenticator.so …
```

(note: this exact config probably skips TOTP for root)

You could try that?

**Comment by raviteja-b** [comment]
> The user doesn't exist _and_ doesn't have a secret key set up, eh?
> 
> Maybe a job for `pam_succeed_if`?
> 
> ```
> auth [default=1 success=ignore] pam_succeed_if.so quiet uid > 0
> auth pam_google_authenticator.so …
> ```
> 
> (note: this exact config probably skips TOTP for root)
> 
> You could try that?

with above check, it won't look for totp for all system users which has UID > 0 
systems user will have did like 1000, 1001

**Comment by ThomasHabets** [comment]
Alright, so swap to `default=ignore success=1`?

**Comment by ThomasHabets** [comment]
Actually, wasn't it right the first time? If UID, go to next line?

**Comment by raviteja-b** [comment]
> Actually, wasn't it right the first time? If UID>0, go to next line?

yeah looks like this is right.
let me quickly try

**Comment by raviteja-b** [comment]
> > Actually, wasn't it right the first time? If UID>0, go to next line?
> 
> yeah looks like this is right. let me quickly try

this config causing issues for ldap auth for ldap users.
there is no control flag to tell google authenticator to skip auth for non-existing users?

**Comment by ThomasHabets** [comment]
What kind of config issues? It should allow you to skip GA for these users.

**Comment by ThomasHabets** [comment]
That shouldn't be the case. `default=1` should mean "skip the next one". But if it's not working then that's a PAM question. Check your logs on why it's not skipping as you expect. I'm not a PAM expert.

**Comment by raviteja-b** [comment]
> That shouldn't be the case. `default=1` should mean "skip the next one". But if it's not working then that's a PAM question. Check your logs on why it's not skipping as you expect. I'm not a PAM expert.

by the way this check does not work for me since I don't want to skip root user as well

**Comment by ThomasHabets** [comment]
If SSH gives a different response for existing and nonexisting users, then an attacker can guess usernames, and see which ones are real.

**Comment by raviteja-b** [comment]
> The reason GA asks for a TOTP even for nonexisting users is partly to fight user enumeration.
> 
> But you could also try the `nullok` option, per the README. But that's not quite the same thing, as it would allow users to log in without TOTP, too.
> 
> To fix the root user issue, you could add that it skips the skipping:
> 
> ```
> auth [success=1 default=ignore] pam_succeed_if.so user = root
> auth [default=1 success=ignore] pam_succeed_if.so quiet uid > 0
> auth pam_google_authenticator.so …
> ```
> 
> (untested)

can we keep "auth pam_google_authenticator.so …" at the last of pam configuration?
so that first ldap or unix user authentication happens then it looks totp authentication

**Comment by ThomasHabets** [comment]
Well, in my example I did.

You should be able to configure whatever your want. It's just a matter of configuring PAM for it.
