### ISSUE TITLE
How to support public key login

### ISSUE THREAD

**Issue by huweikkk** [google/google-authenticator-libpam#261]
### System information
Operating system (e.g. Ubuntu 22.04):CentOS Linux release 7.9.2009 (Core)
Do you use selinux? (check with e.g. `sestatus`): no

### Steps to reproduce

1. …

### What I expected would happen

I want to log in to the server through the public key. After successfully verifying the public key, I need to enter the Google verification password

### What actually happened

After successful configuration, I only need to enter the user's password and Google verification code to log in, without going through the steps of public key login

### PAM config

Paste the relevant parts of your PAM config

```
cat /etc/pam.d/sshd |grep -v "#"
auth	   required	pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
-session   optional     pam_reauthorize.so prepare
auth required pam_google_authenticator.so
```

### If SSH: SSH config

Paste the relevant parts of `/etc/ssh/sshd_config` or equivalent.

```
cat /etc/ssh/sshd_config |grep -v "#"|grep -v "^$"
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication no
ChallengeResponseAuthentication yes
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem	sftp	/usr/libexec/openssh/sftp-server
```

### If not SSH: That program's config, and logs

```
paste here
```

### Contents of `/var/log/auth.log` or equivalent

```
Dec  9 16:14:18 localhost sshd(pam_google_authenticator)[3210]: Accepted google_authenticator for root
Dec  9 16:14:18 localhost sshd[3208]: Accepted keyboard-interactive/pam for root from 192.168.2.204 port 59011 ssh2
Dec  9 16:14:18 localhost sshd[3208]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

**Comment by ThomasHabets** [comment]
This sounds like an OpenSSH question, not a question for this PAM module. But let me try anyway.

It sounds like what you want to do is require an OpenSSH pubkey to be provided in order to even be asked for your password. If the pubkey is not provided, you want reject the login? So with pubkey+password+OTP, you want not quite three factor, but three credential sources?

You say that you're asked for password+OTP even without providing a pubkey. And presumably, you also get to log in using *only* a pubkey, then not being asked for a password?

Check out the `sshd_config` manpage. Specifically [this section](https://manpages.debian.org/jessie/openssh-server/sshd_config.5.en.html#AuthenticationMethods_2):

```
For example, an argument of “publickey,password publickey,keyboard-interactive” would
require the user to complete public key authentication, followed by either password or
keyboard interactive authentication. Only methods that are next in one or more lists are
offered at each stage, so for this example, it would not be possible to attempt password
or keyboard-interactive authentication before public key. 
```

IIRC PAM comes under "keyboard-interactive", so I think you want `AuthenticationMethods publickey,keyboard-interactive` in your `sshd_config`.

**Comment by huweikkk** [comment]
I have set OTP for both root and www users
I put my public key into the root user's/root/. ssh/authorized_keys, but the www user did not
When I log in as a www user, I am asked to enter the password and OTP verification code of the www user
When I logged in as the root user, I directly entered the system without being asked to enter any password

```
[root@internal-wiki-192 ~]# ssh www@192.168.2.62
Password:
Verification code:
Last login: Mon Dec  9 14:58:04 2024 from 192.168.2.204
[www@internal-test-192 ~]$ 登出
Connection to 192.168.2.62 closed.
[root@internal-wiki-192 ~]# ssh root@192.168.2.62
Last login: Tue Dec 10 10:15:39 2024 from 192.168.2.204
```

**Comment by ThomasHabets** [comment]
Like I said, sounds like you need `AuthenticationMethods publickey,keyboard-interactive` in your `sshd_config`.

**Comment by huweikkk** [comment]
According to your guidance, I have modified some configurations to meet these requirements
take
Validator Methods public key, keyboard interactive added to/etc/ssh/sshd_comfig
Annotate the password authentication option in/etc/pam.d/sshd configuration

` cat /etc/ssh/sshd_config |grep -v "#"|grep -v "^$"
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
AuthorizedKeysFile	.ssh/authorized_keys
AuthenticationMethods publickey,keyboard-interactive
PasswordAuthentication no
ChallengeResponseAuthentication yes
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem	sftp	/usr/libexec/openssh/sftp-server`

` cat /etc/pam.d/sshd
#%PAM-1.0
auth	   required	pam_sepermit.so
#auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
auth required pam_google_authenticator.so`

After the above configuration
After public key authentication, I only need to enter the Verification code
If the public key authentication fails, the side will directly refuse login

**Comment by ThomasHabets** [comment]
I mean, it looks like you have commented out the `password-auth`? So I'm not so surprised if it do longer asks for a password.

You're not actually saying if anything is wrong. If you commented out password authentication on purpose, then it sounds like everything is working as intended.
