### ISSUE TITLE
Generate new eight-digit emergency codes for Authenticator for PAM.

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#29]
_From @ThomasHabets on October 10, 2014 8:6_

Original [issue 248](https://code.google.com/p/google-authenticator/issues/detail?id=248) created by tim@timpollock.info on 2013-02-08T00:05:10.000Z:

<b>What steps will reproduce the problem?</b>
1. Wish to generate new emergency codes for times when I don't have Authenticator on me.
2. Setting up Authenticator only gives me five codes.
3. I would like more.

<b>What version of the product are you using? On what operating system?</b>
pam_google_authenticator.so

<b>Please provide any additional information below.</b>
When setting up Google Authenticator for PAM, it gives me five emergency codes. I'd like to generate more as a just-in-case. Is this at all possible?

_Copied from original issue: google/google-authenticator#247_

**Comment by ThomasHabets** [comment]
Comment [#1](https://code.google.com/p/google-authenticator/issues/detail?id=248#c1) originally posted by belotton on 2013-02-09T09:47:43.000Z:

You can change the SCRATCHCODES value (file google-authenticator.c, line 41).
Then, build and install by running "make install".
Run google-authenticator.

Is it possible to generate new emergency codes without changing the secret key ?

**Comment by ThomasHabets** [comment]
Comment [#2](https://code.google.com/p/google-authenticator/issues/detail?id=248#c2) originally posted by belotton on 2013-02-09T11:01:20.000Z:

You can change the SCRATCHCODES value (file google-authenticator.c, line 41).
Then, build and install by running "make install".
Then, run google-authenticator.

I think google-authenticator should be able to generate new emergency codes without generating a new secret.

**Comment by ThomasHabets** [comment]
Comment [#3](https://code.google.com/p/google-authenticator/issues/detail?id=248#c3) originally posted by belotton on 2013-02-09T13:47:28.000Z:

Here is a patch allowing you to specify the number of emergency codes (max 10) you want to generate.

Usage :
google-authenticator --emergency-code 10
google-authenticator -e 10

**Comment by fartbagxp** [comment]
Hi Thomas, it seems like @Lo0k has done his patch in #60.
Is it possible for it to merged into the master branch?

Thanks!

**Comment by ThomasHabets** [comment]
It was already merged a year ago.
