### ISSUE TITLE
Authenticator for Windows Login

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#34]
_From @ThomasHabets on October 10, 2014 8:6_

Original [issue 183](https://code.google.com/p/google-authenticator/issues/detail?id=183) created by kirkholmes on 2012-06-05T17:41:49.000Z:

I've been looking all over the net for a solution or option. I use Google Authenticator for everything Google and would like the ability to also use it as a second method of security when logging into my Windows Computer.

Is this an option? If so how can this be done and/or can it be an option?

_Copied from original issue: google/google-authenticator#182_

**Comment by ThomasHabets** [comment]
Comment [#1](https://code.google.com/p/google-authenticator/issues/detail?id=183#c1) originally posted by GEOFFLK4 on 2012-06-12T21:13:44.000Z:

 looking for same

**Comment by ThomasHabets** [comment]
Comment [#2](https://code.google.com/p/google-authenticator/issues/detail?id=183#c2) originally posted by jeff@jsrog.com on 2012-08-17T19:37:37.000Z:

Same here

**Comment by ThomasHabets** [comment]
Comment [#3](https://code.google.com/p/google-authenticator/issues/detail?id=183#c3) originally posted by dominik.pretzsch on 2012-08-17T20:47:47.000Z:

Maybe this is an option for you:
http://code.google.com/p/multi-one-time-password--credential-provider/

**Comment by ThomasHabets** [comment]
Comment [#4](https://code.google.com/p/google-authenticator/issues/detail?id=183#c4) originally posted by marcospinto@dipconsultants.com on 2012-08-30T02:06:22.000Z:

i want this *really* badly for corporate security

**Comment by ThomasHabets** [comment]
Comment [#5](https://code.google.com/p/google-authenticator/issues/detail?id=183#c5) originally posted by mr2dave on 2012-09-12T22:32:11.000Z:

I ended up here while searching for the same.

**Comment by ThomasHabets** [comment]
Comment [#6](https://code.google.com/p/google-authenticator/issues/detail?id=183#c6) originally posted by niranjan.patil on 2013-01-09T11:41:29.000Z:

I wish it could, though it's unlikely have this ported to Windows environment.

**Comment by ThomasHabets** [comment]
Comment [#7](https://code.google.com/p/google-authenticator/issues/detail?id=183#c7) originally posted by f3rrix on 2013-01-11T19:48:22.000Z:

Since google authenticator is just an OATH time-based one-time-password generator, you should be able to use it with any 2-factor logon solution for Windows that has support for OATH tokens.  There's not much (if any) "google-specific" work to be done.  And it's certainly not a defect in the authenticator.

For example (but certainly not the only example!) my company makes AuthLite, version 2 of which specifically has support for enterprise networks using google authenticator including with Windows.

I guess there are a lot of security enthusiasts out there who would like to use google authenticator for standalone workstations too.  This inspires me!  

I will make a quick free product to use google authenticator tokens to do windows workstation logon :) Should be easy considering we already have all the ground work done.  Do you think Google would mind if we called it "Google Authenticator for Windows Logon"?  I'm not sure what else it could possibly be called =P

**Comment by ThomasHabets** [comment]
Comment [#8](https://code.google.com/p/google-authenticator/issues/detail?id=183#c8) originally posted by jason.adams1301 on 2013-02-27T20:29:57.000Z:

Would Love this as well

**Comment by ThomasHabets** [comment]
Comment [#9](https://code.google.com/p/google-authenticator/issues/detail?id=183#c9) originally posted by asilonos on 2013-03-11T11:03:56.000Z:

Try rohos logon - 
http://www.rohos.com/2013/02/google-authenticator-windows-login/

**Comment by ThomasHabets** [comment]
A quick googling shows many descriptions on how to do this. E.g. https://www.maketecheasier.com/google-authenticator-windows/

**Comment by morikawa-k** [comment]
A credential provider that exactly meets the requirements is here:

https://www.ribig.co.jp/gauthlogon
 
For disclosure, I developed the program

**Comment by biggestsonicfan** [comment]
I feel like this issue should be reopened and explored. I would like to SSH into my Windows system and access my WSL2 distro's bash, however the SSH credentials would be through Windows, not the WSL2's SSH config.

This issue was transferred from the old authenticator repo, but I believe it has taken on new meaning under libpam.
