### ISSUE TITLE
Feature request: ask for verification code only once a day for each client ip

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#40]
_From @ThomasHabets on October 10, 2014 8:6_

Original [issue 115](https://code.google.com/p/google-authenticator/issues/detail?id=115) created by d.ananyev on 2011-11-02T10:34:17.000Z:

Is it possible to add an option to pam module that would skip verification code check for username+ip that was successfully authorized last 24 hours.

It's like gmail login verification checkbox &quot;dont ask verificaction code for 30 days&quot;.

_Copied from original issue: google/google-authenticator#114_

**Comment by ThomasHabets** [comment]
Comment [#1](https://code.google.com/p/google-authenticator/issues/detail?id=115#c1) originally posted by markus@google.com on 2011-12-15T09:15:03.000Z:

&lt;empty&gt;

**Comment by ThomasHabets** [comment]
_From @bandtree on June 24, 2016 20:2_

This is something that I would love implemented. You could use PAM_RHOST possibly to get the IP address. I have seen other PAM modules that do this. Thanks!

**Comment by bersbersbers** [comment]
This can be closed since 7534d26 has been merged, right?

**Comment by ThomasHabets** [comment]
Yup, thanks.
