### ISSUE TITLE
Update man pages

### ISSUE THREAD

**Issue by ThomasHabets** [google/google-authenticator-libpam#45]
_From @ThomasHabets on October 10, 2014 8:7_

Original [issue 285](https://code.google.com/p/google-authenticator/issues/detail?id=285) created by tomekczyz on 2013-07-20T23:26:30.000Z:

There are a lot of nice examples in README file (for example with `secret=` or with `nullok`) but there is not a word about it in a `man`. In `man` there is a link to a wiki page which also does not cover the topic.

It would be nice to copy/paste it to `man`, or just write that there is a README with some examples. But I would prefer to paste examples to `man` as not every distribution include README in package (debian has not include it yet) - but is not the point.

_Copied from original issue: google/google-authenticator#284_

**Comment by ThomasHabets** [comment]
Dup of https://github.com/google/google-authenticator-libpam/issues/58

**Comment by Lo0k** [comment]
I think a manpage should also be added in section 8 to document the PAM module options, ie. pam_google_authenticator.8. I can create it from README.md.

**Comment by ThomasHabets** [comment]
Yeah. I seem to have duped against the wrong bug, but #59 is still open to create more manpages.

Yes, a pull request would be appreciated. Feel free to annotate commit messages with "Bug #59".
