### ISSUE TITLE
Google Prompt - prompt yes or no on cell phone instead of digiting code

### ISSUE THREAD

**Issue by leopucci** [google/google-authenticator-libpam#48]
Is there a way to use prompt message acess on the cellphone, (just like you use in gmail) so i just need to tap on my cell autenticating my access? without needing to digit otp?

**Comment by ThomasHabets** [comment]
That functionality doesn't exist in the PAM module nor in the open source Google Authenticator, no.

Possibly Duo Security has this, but I don't know.

**Comment by leopucci** [comment]
Thanks anyway!

2016-12-11 15:32 GMT-02:00 Thomas Habets <notifications@github.com>:
