### ISSUE TITLE
Suggest that users copy the GA seed key directly rather than using the URL

### ISSUE THREAD

**Issue by reppep** [google/google-authenticator-libpam#50]
Going through Google to produce a scannable QR code seems like an iffy bet, as it embeds lots of security information we'd prefer neither Google nor anyone sniffing (perhaps with Blue Coat or other MitM proxy) capture. The README should probably suggest paranoid users manually set up their TOTP authenticator with the seed key instead.

**Comment by ThomasHabets** [comment]
If you have libqrencode installed the QR code is printed in ASCII-art without contacting Google servers.

This would be the easiest and most convenient method and makes sure Google doesn't see the secret.

Were you aware of this, and you're asking for the fallback of the charts API URL to come with a warning?

**Comment by reppep** [comment]
I don't have that library installed. I've switched to pasting the secret directly into 1Password, which works fine. The docs should suggest avoiding the Google URL -- I visited 2-3 before I realized they encode more authentication information than I'm comfortable with.
