### ISSUE TITLE
How can we modify or remove completely the server name as a title in the app on mobile devices

### ISSUE THREAD

**Issue by loopholdgit** [google/google-authenticator-libpam#58]
I believe the module sends the server and attaches that as a title in the google-authenticator app on mobile devices. How can we modify what name to be shown there?

**Comment by ThomasHabets** [comment]
With `-s`. The other data is changed with `-l'.

**Comment by loopholdgit** [comment]
Thank you very much for the response. So we need to issue the following command on the server:
.google-authenticator - s "servername"?

Is the above correct?

Where can I find documentation on all the options? I searched but was unsuccessful.

**Comment by ThomasHabets** [comment]
Yes, when you set up Google Authenticator for the user you provide these options.

You can see the options by running `google-authenticator -h`, or see the same [here](https://github.com/google/google-authenticator-libpam/blob/master/src/google-authenticator.c#L388).

I've created #59 to create a manpage for better documentation, as I don't see it being documented elsewhere.
