### ISSUE TITLE
Most uses in sudo expose the key to the user

### ISSUE THREAD

**Issue by briansniffen** [google/google-authenticator-libpam#65]
Thanks for the great project; this was a cinch to integrate on debian for ssh & local login.  But for sudo, there's a problem: the secret is readable by the user in ~/.google-authenticator.  Is there a way to have per-user sudo keys *not* readable by that user, or is it required to use something like `auth required libpam-google-authenticator.so user=root secret=/root/.google-authenticator` ?

Thanks!

**Comment by akerl** [comment]
I'm not 100% sure on the ordering, but have you tried using the "${USER}" variable in your secret path? Either it gets evaluated using the username of the origin user, or the user it's about to run the check as. If the former, it'll work. If the latter, it'll obviously not work.

**Comment by briansniffen** [comment]
It uses the $USER of the requesting user, same as ordinary PAM sudo asks
for the password of the requesting user.

I think to do better it might need to keep secrets in a root owned
/etc/google-authenticator/secrets/$USER.secret or similar.

**Comment by akerl** [comment]
Yes, that was my point; if you set the secret path like that, it'll let you store per-user secrets where the pre-sudo user can't read them

**Comment by ThomasHabets** [comment]
Yes, that's what that feature is for.

I assume this question is now answered?
