### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by candrews** [google/google-authenticator-libpam#67]
The last release was [1.0.3](https://github.com/google/google-authenticator-libpam/releases/tag/1.03) almost a year ago. There have a been a number of changes since then:
https://github.com/google/google-authenticator-libpam/compare/1.03...master
Could you  please make a new release?

**Comment by ThomasHabets** [comment]
Seems like a good idea. Done.

**Comment by candrews** [comment]
Thank you!
