### ISSUE TITLE
Module gives hints about security config of accounts.

### ISSUE THREAD

**Issue by nielsbasjes** [google/google-authenticator-libpam#69]
I configured the pam module in conjuction with sshd and it works great.

Yet I see a pattern which seems to 'leak' information about the chosen security config.

On my server I have NOT set the nullok because I want all accounts to have the OTP.
When someone does `ssh foo@my.server.nl` the system will simply ask for the password because there is no user called `foo`. Doing the same for a user account that does exist then the prompt for the OTP code is presented before presenting the password (I have configured it this way).

This difference leaks information about the accounts and how they have been configured: 
- If it asks for a code: account exists and OTP has been configured.
- If it does NOT ask for a code: either account does not exist and/or OTP has not been configured.

I think that when this module has been configured without 'nullok' that the system must always ask for an OTP code, even though any code you enter will be wrong (as it has not been configured and/or the account simply does not exist).

**Comment by ThomasHabets** [comment]
Could you share your PAM setup?

**Comment by ThomasHabets** [comment]
But yeah this seems likely, and it's a consequence of the [conditional of doom](https://github.com/google/google-authenticator-libpam/blob/master/src/pam_google_authenticator.c#L1564) that should be split up.

**Comment by nielsbasjes** [comment]
Yes.I have quick test implementation on my machine. I'll see if I can put up a pull request later this week.

**Comment by nielsbasjes** [comment]
The config of the separate CentOS7 VM I created to test my changes:

/etc/pam.d/sshd 
I simply added the top line
```
#%PAM-1.0
auth       required     /usr/local/lib/security/pam_google_authenticator.so secret=/var/lib/google-authenticator/${USER} [authtok_prompt=Give me the code: ] echo_verification_code user=root  debug 
auth	   required	pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
```

I only changed the `ChallengeResponseAuthentication yes`
# cat /etc/ssh/sshd_config | grep -v '^#' | grep .
```
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication yes
ChallengeResponseAuthentication yes
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
UsePrivilegeSeparation sandbox		# Default for new installations.
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem	sftp	/usr/libexec/openssh/sftp-server
```

# ls -laZ /var/lib/google-authenticator/
```
drwxr-xr-x. root root unconfined_u:object_r:var_lib_t:s0 .
drwxr-xr-x. root root system_u:object_r:var_lib_t:s0   ..
-r--------. root root unconfined_u:object_r:ssh_home_t:s0 root
```

**Comment by nielsbasjes** [comment]
@ThomasHabets I put up a pull request with my take on this. 
Note that I have not updated the tests at this time.

**Comment by ThomasHabets** [comment]
Something like that, yeah.
I think the tests are broken because of [unrelated issues on CentOS](https://github.com/google/google-authenticator-libpam/issues/7)

**Comment by ThomasHabets** [comment]
Oh yeah, no that's not it, it failed on travis-ci.

But if you're testing on CentOS, be aware that there is that outstanding issue with the tests.

**Comment by nielsbasjes** [comment]
I updated based on your comments.
I'll have a look at the tests later.

**Comment by ThomasHabets** [comment]
Cool. I'll merge once tests pass.

**Comment by nielsbasjes** [comment]
I just tried my latest version and the tests all pass on both my Ubuntu 16.04 and my CentOS 7 systems.

**Comment by nielsbasjes** [comment]
I just installed this version on my test VM (CentOS 7) with Selinux enabled and it works as I had in mind.

**Comment by ThomasHabets** [comment]
I added a more forceful privilege dropping. Could you verify that I didn't break it for you?

**Comment by nielsbasjes** [comment]
I installed the latest master on my test machine and it behaves as I expect it to.
Also your code change seems ok.

Small remark:
There is the comment "// Don't allow to continue as root."
Yet I have it configured as  `user=root` and this works fine.

**Comment by ThomasHabets** [comment]
Right. That feature. Comment updated.
