### ISSUE TITLE
nullok option ignored on Centos 7

### ISSUE THREAD

**Issue by arjun1995** [google/google-authenticator-libpam#75]
Set up the multifactor authentication following this [digital ocean article](https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7). Currently set our sshd_config to have `AuthenticationMethods publickey, keyboard-interactive` and in `/etc/pam.d/sshd` we are using the line `auth required pam_google_authenticator.so nullok`.

The expectation is that users with `.google_authenticator` file will be prompted for their verification code, and that users without said file would be able to login with only their public key. Instead, the users with the file get prompted for their verification code but users without the file get denied. 

Below is a verbose ssh output:

```
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/arjunpathmarajan/.ssh/config
debug1: /Users/arjunpathmarajan/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 53: Applying options for *
debug1: Connecting to 34.204.80.26 [34.204.80.26] port 22.
debug1: Connection established.
debug1: identity file /Users/arjunpathmarajan/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/arjunpathmarajan/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1
debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to 34.204.80.26:22 as 'arjun'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:8nObniV1G2Z/cp7n5Sqs8wYS/U0jRDuf24+k+cDFPwk
debug1: Host '34.204.80.26' is known and matches the ECDSA host key.
debug1: Found key in /Users/arjunpathmarajan/.ssh/known_hosts:5
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/arjunpathmarajan/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 535
Authenticated with partial success.
debug1: Authentications that can continue: keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: keyboard-interactive
debug1: No more authentication methods to try.
Permission denied (keyboard-interactive).
```

For debugging purposes here is the `/etc/pam.d/sshd`:
```
#%PAM-1.0
auth       required     pam_sepermit.so
# auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
auth required pam_google_authenticator.so nullok
```

and `/etc/ssh/sshd_config`:
```
#
# Generated by Chef for bastion-000.prod.aws.
# Local modifications will be overwritten.
#
Port 22
AcceptEnv LANG LANGUAGE LC_* XMODIFIERS
AuthenticationMethods publickey,keyboard-interactive
ChallengeResponseAuthentication yes
GSSAPIAuthentication yes
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_ecdsa_key
PasswordAuthentication yes
PermitRootLogin no
Protocol 2
Subsystem sftp /usr/libexec/openssh/sftp-server
SyslogFacility AUTHPRIV
UseDNS no
UsePAM yes
X11Forwarding yes
```

**Comment by ThomasHabets** [comment]
If you re-add password auth (that you have removed, right?), does it prompt for password?

I'm thinking since GA PAM module returns `PAM_IGNORE` for nullok when file is missing, you'll need to add `auth required pam_permit.so` to the end of your `/etc/ssh/sshd_config`. The reason being that IIRC you need at least one module to say "yes", and in this case GA is saying neither yes or no.

**Comment by dannenberg** [comment]
Thank you @ThomasHabets

**Comment by karmendra** [comment]
> If you re-add password auth (that you have removed, right?) just to test, does it prompt for password?
> 
> I'm thinking since GA PAM module returns `PAM_IGNORE` for nullok when file is missing, you'll need to add `auth required pam_permit.so` to the end of your `/etc/ssh/sshd_config`. The reason being that IIRC you need at least one module to say "yes", and in this case GA is saying neither yes or no.

I think you meant to add `auth required pam_permit.so` to the end of your `/etc/pam.d/sshd`. (At least in Ubuntu 18, I had to put it in this line for it to work).

I have one more question.
I have 2 users on my system, and after adding auth required pam_permit.so, login behavior is as following:
1. user1 with .google_authenticator present - user1 is prompted for verification code
2. user2 without google-authenticator configured - user2 is not prompted for verification code and is allowed to login
Now, for 'root' user - there is no google-authenticator configure - and it neither prompts for verification code nor allows login, it just drops my ssh connection.

I an unable to find a solution where I enable 2fa for normal users, and still allow root user to login without any 2fa. Please Help.

Thanks.

**Comment by ThomasHabets** [comment]
Yes, I meant the PAM config for that line.

Sounds like you have a completely different problem, not related to this issue.

Does your SSH even allow root logins?

**Comment by karmendra** [comment]
Thanks @ThomasHabets Problem was really that I had disabled root login in ssh_config.

BTW `auth required pam_permit.so` is VERY VERY dangerous, if not correctly configure it  would allow login without asking for any password or private key. Should always test if use is allowed to login without credentials if this line of code is put in pam.d/sshd file.

**Comment by ThomasHabets** [comment]
Agreed. All changes to PAM config should be checked not just that the right credentials get you in, but the wrong ones don't.

I've certainly made mistakes during editing, and make sure to confirm both false positives and negatives before I'm done.
