### ISSUE TITLE
ssh-agent equivalent for mfa?/can we set a period of access after one MFA code?

### ISSUE THREAD

**Issue by dannenberg** [google/google-authenticator-libpam#82]
We've set up a bastion host which requires MFA. We use this host to connect to all other nodes in our cluster. It is really annoying/inconvenient to have to enter a new MFA code for each server we log into. Is there some way to only require MFA code once every N seconds or something of that sort?

**Comment by ThomasHabets** [comment]
There is no such thing, no.

I would suggest to log in to the bastion host and run `screen` or `tmux` on it.

Or you could look at the withdrawn pull request https://github.com/google/google-authenticator-libpam/pull/83, and the comment I made there.
