### ISSUE TITLE
Create a new release for macOS homebrew

### ISSUE THREAD

**Issue by jabenninghoff** [google/google-authenticator-libpam#84]
I've created a [homebrew PR](https://github.com/Homebrew/homebrew-core/pull/19177) that successfully builds google-authenticator-libpam on macOS.

Since homebrew only allows builds from released versions, could you issue a new release, to take advantage of recent code changes, including PR #80? This will resolve a workaround in the formula.

Thanks!

**Comment by ThomasHabets** [comment]
I want to get https://github.com/google/google-authenticator-libpam/pull/79 in first, but this is second on the list.

I'm just swamped with backlog so expect this to take a few days.

**Comment by jabenninghoff** [comment]
No problem, thanks!

**Comment by ilovezfs** [comment]
@ThomasHabets how's the progress on #79 and a new release?

**Comment by ThomasHabets** [comment]
I'm on a trip, but will do this on Monday.

**Comment by ThomasHabets** [comment]
Done.

**Comment by ilovezfs** [comment]
Thanks @ThomasHabets!
