### ISSUE TITLE
Problem with ssh Ubuntu 16.04

### ISSUE THREAD

**Issue by msternik** [google/google-authenticator-libpam#88]
Hi, I have a google authenticator setup on multiple VMs that run Ubuntu 16.04.

The authenticator works for some time and then it starts to reject the correct passwords for all accounts. This has happened on multiple VMs already. (The VMs are not on the same host).

We use the following authentication methods (in this order): certificate, password, verification code.
In the syslog I can see that before the password is even accepted there is an error "Invalid Verification Code". 

I attach the ssh and pam config files.
[pamd.txt](https://github.com/google/google-authenticator-libpam/files/1618442/pamd.txt)
[ssh_config.txt](https://github.com/google/google-authenticator-libpam/files/1618455/ssh_config.txt)

What could be causing this?

Thanks.

P.S. this was reposted from [here](https://github.com/google/google-authenticator/issues/625#event-1414064038).

**Comment by MarcelFranken** [comment]
I got the same problem.
After i deleted the file called ".google_authenticator~" the login works..

**Comment by ThomasHabets** [comment]
@msternik could you check if the user has a `~/.google_authenticator~` (they should not), and a `~/.google_authenticator` file (they should)?

If that looks OK, add `debug` to your pam config line and see what else the logs say.

At login are the users asked for validation codes?

**Comment by msternik** [comment]
Hi ThomasHabets, I checked and there was no ~/.google_authenticator~ file and ~/.google_authenticator existed as expected. I had to abandon this solution and go for other option as I didn't make any progress on this for a couple of days. 

If this is of help, I can let you know in more detail how to reproduce this issue. I am closing it for now, but feel free to reopen if needed.

**Comment by MarcelFranken** [comment]
Maybe someone can help me? I have that file called ~/.google_authenticator~

How can i solve this in future?

**Comment by MarcelFranken** [comment]
I mean ".google_authenticator~"

**Comment by ThomasHabets** [comment]
In the future this should not be a problem since 3c3194098fc48f2ea388b7037975896dea014400 (committed 9 Dec 2017) changed it to use a generated filename.

There's been no release with this change yet.

In the mean time: If you see `~/.google_authenticator~` then delete it. It should only exist for a millisecond or so.
