### ISSUE TITLE
old nullok behavior is useful

### ISSUE THREAD

**Issue by DavidGalicia** [google/google-authenticator-libpam#89]
Hi, I noticed the 'nullok' parameter now causes the module to return IGNORE instead of SUCCESS.

https://github.com/google/google-authenticator-libpam/issues/55

I'm running into trouble with the new behavior and I find the old behavior useful for my situation. I'm using a Centos 6.9 box with Winbind.

Below a /etc/pam.d/password-auth is a file using authconfig's 'enablepamaccess' option:

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth required pam_env.so
auth sufficient pam_unix.so nullok try_first_pass
auth requisite pam_succeed_if.so uid >= 500 quiet
auth sufficient pam_winbind.so use_first_pass
auth required pam_deny.so
```

I want to prompt the ssh user for a username, password, and verification code in that order (to make the steps consistent with Google's sign-in process) so I make this change:

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth required pam_env.so
auth sufficient pam_unix.so nullok try_first_pass
auth requisite pam_succeed_if.so uid >= 500 quiet
auth required pam_winbind.so use_first_pass
auth sufficient pam_google_authenticator.so nullok
auth required pam_deny.so
```

Notice I try to use 'sufficient' to tell pam to stop processing more modules if 'pam_google_authenticator.so' returns SUCCESS. 

Ideally, if a ssh user has no google-authenticator settings and tries to login, my change will cause pam not to process 'pam_deny.so' after 'pam_google_authenticator.so' and ultimately allow the ssh user access. However, my change always denies the ssh user access.

If I edit the order, the ssh user is given access as expected (but the ssh user must now enter a verification code before entering a password):

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth required pam_env.so
auth sufficient pam_unix.so nullok try_first_pass
auth requisite pam_succeed_if.so uid >= 500 quiet
auth required pam_google_authenticator.so nullok
auth sufficient pam_winbind.so use_first_pass
auth required pam_deny.so
```

I try to use pam's advanced options to make my original order work using 'ignore=done':

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth required pam_env.so
auth sufficient pam_unix.so nullok try_first_pass
auth requisite pam_succeed_if.so uid >= 500 quiet
auth required pam_winbind.so use_first_pass
auth [default=bad success=done ignore=done] pam_google_authenticator.so nullok
auth required pam_deny.so
```

However, this change always denies the ssh user access too. In /var/log/secure, I see this related event:

```
Jan 16 12:18:42 stage01 sshd[1884]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.28.1 user=administrator
Jan 16 12:18:42 stage01 sshd[1884]: pam_winbind(sshd:auth): getting password (0x00000010)
Jan 16 12:18:42 stage01 sshd[1884]: pam_winbind(sshd:auth): pam_get_item returned a password
Jan 16 12:18:42 stage01 sshd[1884]: pam_winbind(sshd:auth): user 'administrator' granted access
Jan 16 12:18:45 stage01 sshd[1882]: error: PAM: The return value should be ignored by PAM dispatch for administrator from 192.168.28.1
```

To make pam configuration flexible and less invasive as possible -- can module parameters like 'successifnull' and 'ignoreifnull' be introduced? When a user has no google-authenticator settings, the 'successifnull' parameter makes the module return SUCCESS and the 'ignoreifnull' parameter makes the module return IGNORE.

Here are links I that helped me learn how pam options work:
https://serverfault.com/questions/644226/how-do-pam-advanced-options-work-exactly
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/managing_smart_cards/pam_configuration_files

EDITS (2018 oct 17, 10:31am cst):
- Made a typo in the first code block. I replaced 'required' with 'sufficient' for pam_winbind.so. 
- Mistakenly introduced the first code block as a file generated by Winbind. The first code block is now introduced as a file generated by authconfig using the 'enablepamaccess' option.The 'authconfig' command exists in redhat/centos but not in debian.

**Comment by ThomasHabets** [comment]
I'm not familiar with Windbind, but if processing goes to the `pam_deny` line then why do expect login to succeed?

Why do you have a `pam_deny` line? Why not:

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth required pam_env.so
auth sufficient pam_unix.so nullok try_first_pass
auth requisite pam_succeed_if.so uid >= 500 quiet
auth required pam_winbind.so use_first_pass
auth required pam_google_authenticator.so nullok
```

I'm not sure why your last attempt doesn't work. That seems weird. Add `debug` as an option and see if you get any better log messages.

**Comment by DavidGalicia** [comment]
> I'm not familiar with Windbind, but if processing goes to the pam_deny line then why do expect login to succeed?

I checked the first comment block and saw a typo. I updated the first code block so that the pam_winbind line uses 'sufficient' instead of 'required'. The designer of the file (or party that wrote the generator) expects pam to not process the pam_deny line if the previous module uses 'sufficient' and returns SUCCESS. I reuse the same design in the second code block by making the pam_winbind line use 'required' and the making the pam_google_authenticator line use 'sufficient'.

I learned the /etc/pam.d/password-auth file is not generated by a tool in the winbind suite. The file was made by authconfig which is a tool that comes with redhat/centos. I looked at a vm running a centos/lamp configuration and saw the file exists there too:
```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth        required      pam_env.so
auth        sufficient    pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        required      pam_deny.so
```
Notice the file also has a pam_deny line.

> Why do you have a pam_deny line?

Your code block, which omits the pam_deny line, works.

I did some research why the /etc/pam.d/password-auth file is designed with the pam_deny line:

https://linux.die.net/man/8/pam_deny

https://books.google.com/books?id=wYBbM8ol2McC&pg=PA441&lpg=PA441&dq=pam_deny+module&source=bl&ots=PTD_YHgIeC&sig=3p0-OYqOwgDAMAiDopjO6DPlSyU&hl=en&sa=X&ved=0ahUKEwi10sfPr9_YAhUPMqwKHQCIA38Q6AEIWDAI#v=onepage&q=pam_deny%20module&f=false

A good (but not satisfying) explanation I found for the design is this:
> The pam_deny module always returns a negative authentication result to the application through the PAM framework. As such, it might be suitable for using for default entries to ensure a deny-all authentication stance.

Without the pam_deny line, access control appears to work as expected: a wrong username, password, or verification code causes access to be denied -- so that's good. But I don't fully understand the consequences of leaving out the line. I'll need to contact the authconfig people and ask if the line is safe to omit.

> I'm not sure why your last attempt doesn't work. That seems weird. Add debug as an option and see if you get any better log messages.

I added the debug option but I saw no interesting messages:
```
Jan 17 14:19:24 test01 sshd[2984]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.28.1  user=administrator
Jan 17 14:19:24 test01 sshd[2984]: pam_winbind(sshd:auth): getting password (0x00000010)
Jan 17 14:19:24 test01 sshd[2984]: pam_winbind(sshd:auth): pam_get_item returned a password
Jan 17 14:19:24 test01 sshd[2984]: pam_winbind(sshd:auth): user 'administrator' granted access
Jan 17 14:19:24 test01 sshd(pam_google_authenticator)[2984]: debug: start of google_authenticator for "administrator"
Jan 17 14:19:25 test01 sshd[2982]: error: PAM: The return value should be ignored by PAM dispatch for administrator from 192.168.28.1
```

I'm not sure where the 'error: PAM: The return value should be ignored by PAM dispatch for administrator from 192.168.28.1' message came from.

I think the biggest problem with my feature request is that I can't prove omitting pam_deny changes security. Currently, my feature request seems to be a convenience -- useful if one wanted a way to edit /etc/pam.d/password-auth while preserving the designer's intention. If you'd like we can close the issue and I'll follow up later if I find convincing reasons to keep pam_google_authenticator and pam_deny in the same file.

**Comment by ThomasHabets** [comment]
Seems debug logging is insufficient to help here. I just pushed one more debug line to see what it actually returns, but it is strange.

We can keep this open and I'll see if I can reproduce this in my almost nonexistent free time. I may have some time in February. :-/

**Comment by tmburnell** [comment]
I have just started using google-authenticator and all documentation say 
```auth required pam_google_authenticator.so nullok```
should allow access if no `.google_authenticator` file exist ... however this does not seem to be true probably because of the change made in #55.  if you look at the logs google_authenticator does not error however you get a PAM Auth failure ... my assumption is because we never get a success. 

So it is almost as if we need to add an approve user if no error was thrown from `pam_google_authenticator`
however I cant find the command

**Comment by ThomasHabets** [comment]
@tmburnell `nullok` works, if you configure PAM correctly. You'll need to add more details about your config to get more help.

**Comment by tmburnell** [comment]
I followed this setup [here:](https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-centos-7#tip-5-%E2%80%94-forcing-mfa-for-all-users)

here are commands I ran: 
```
sed -i '/auth       substack     password-auth/s/^/#/g' /etc/pam.d/sshd
echo "auth sufficient pam_google_authenticator.so nullok" >> /etc/pam.d/sshd

sed -i '/ChallengeResponseAuthentication no/s/^/#/g' /etc/ssh/sshd_config
sed -i '/#ChallengeResponseAuthentication yes/s/^#//g' /etc/ssh/sshd_config
echo "AuthenticationMethods publickey,keyboard-interactive" >> /etc/ssh/sshd_config

systemctl restart sshd.service
```

It would work fine if i had a `.google_authenticator` file, however if I did not i would get: `Permission denied (publickey,gssapi-keyex,gssapi-with-mic)` on the user side.  looking at the `/var/log/secure` log it is not google authenticator failing it fails after it runs ... which i presume is because nothing says success.

**Comment by ThomasHabets** [comment]
@tmburnell you'll need at least one PAM module to say "success". With `nullok` and when there's no existing file as you found this PAM module will say `PAM_IGNORE`. If there is but code is wrong it'll say auth failure, thus preventing auth no matter what happens next.

So… sounds like you should add a `pam_permit.so` line after the GA line. Something like `auth required pam_permit.so`.

Try it, and try entering the wrong code, and the right code, to make sure behaviour is correct.

**Comment by tmburnell** [comment]
I was planning on trying that command but had not had a chance... However All existing example online (I believe) are incorrect now without `auth required pam_permit.so`, where it would have before. 
This ticket might be enough for someone new to figure out why it does not work, but might be nice to have a new setup doc created (or update the old).

**Comment by ThomasHabets** [comment]
Documented in 5e804ec11104a1ab17ce02d0681130ded037f39b.

**Comment by hanabokuro** [comment]
> One way to do this is to add `auth required pam_permit.so` to the end of the PAM config.

With this setting, when `BAD` is returned, it will be `SUCCESS` by pam_permit.so ?

To return `SUCCESS` only for `IGNORE`, the following settings were made.
Seems to work well

```
#%PAM-1.0
auth        required      pam_env.so
auth        [success=done new_authtok_reqd=done ignore=2]    pam_google_authenticator.so nullok
auth        requisite     pam_succeed_if.so uid > 500 quiet
auth        required      pam_deny.so
auth        required      pam_permit.so
```

**Comment by ThomasHabets** [comment]
What I suggested is that if both `pam_google_authenticator.so` and `pam_permit.so` are `required`, then the former returning either `SUCCESS` or `IGNORE` will cause overall `SUCCESS`, but without `pam_permit.so` GA returning `IGNORE` will not cause overall `SUCCESS`. `BAD` is still short-circuit `BAD`, if `required`.

**Comment by hanabokuro** [comment]
I was completely misunderstood.
Thank you.
