### ISSUE TITLE
How to hide the secret key from user profile

### ISSUE THREAD

**Issue by amitbhatt26** [google/google-authenticator-libpam#91]
I want to hide the secret key from the user's profile .google_authenticator. Is there any way to do this currently?

Key should appear only once on Linux box terminal when we will set it initially and system should not save that key in .google_Authenticator file or it should be in encrypted form?

Thanks
Amit Bhatt

**Comment by ThomasHabets** [comment]
You could use options like `secret=/etc/locked-down-dir/${USER}.auth user=some-user` where `some-user` is the only reader/writer of `/etc/locked-down-dir`.

See [the README](https://github.com/google/google-authenticator-libpam/blob/master/README.md)
